export const metadata = {
  title: {
    default: "NextJs",
    template: "%s | NextJs",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
